### ISSUE TITLE
RuntimeError of vk (or sapien)

### ISSUE THREAD

**Issue by HeegerGao** [haosulab/ManiSkill#146]
Hi, I just installed Maniskill2 on Ubuntu 20.04 with `pip install mani-skill2`. I tried `python -m mani_skill2.examples.demo_random_action` and I got the following error:
```
opts: []
env_kwargs: {}
[2023-09-03 19:20:44.329] [svulkan2] [error] GLFW error: X11: The DISPLAY environment variable is missing
[2023-09-03 19:20:44.329] [svulkan2] [warning] Continue without GLFW.
Traceback (most recent call last):
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/examples/demo_random_action.py", line 78, in <module>
    main(parse_args())
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/examples/demo_random_action.py", line 36, in main
    env: BaseEnv = gym.make(
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/utils/registration.py", line 92, in make
    env = env_spec.make(**kwargs)
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/utils/registration.py", line 34, in make
    return self.cls(**_kwargs)
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/envs/pick_and_place/pick_cube.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/envs/pick_and_place/base_env.py", line 27, in __init__
    super().__init__(*args, **kwargs)
  File "/home/users/gck/anaconda3/envs/torch/lib/python3.8/site-packages/mani_skill2/envs/sapien_env.py", line 107, in __init__
    self._renderer = sapien.SapienRenderer(**renderer_kwargs)
RuntimeError: vk::createInstanceUnique: ErrorOutOfHostMemory
```

I am sure I have done the Vulkan thing as you suggest in the Troubleshooting section [here](https://haosulab.github.io/ManiSkill2/getting_started/installation.html). That is, I have installed `libvulkan1` and I have the following three files: `/usr/share/vulkan/icd.d/nvidia_icd.json`, `/usr/share/glvnd/egl_vendor.d/10_nvidia.json`, and `/etc/vulkan/implicit_layer.d/nvidia_layers.json`.

I am using A800 and A100, and cuda 12.0.

**Comment by xuanlinli17** [comment]
Is the GPU free? What's your nvidia-driver version? It's recommended to use 530+.

Could you help us to reproduce it by providing (1) docker & dockerfile, (2) command?
