### ISSUE TITLE
CUDA build failed for soft-body environment with single GPU

### ISSUE THREAD

**Issue by friolero** [haosulab/ManiSkill#157]
The example runs fine on rigid body environment but failed to build on the soft-body environment. 
My GPU is one Nvida RTX 2000 Ada and The Nvidia driver version is 535.113.01. Could you please shed some light here why it failed? Thanks!

```
└─(04:49:02 on main)──> python3 -m mani_skill2.examples.demo_random_action -e Hang-v0                                   ──(Tue,Oct10)─┘
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
opts: []
env_kwargs: {}
Warp initialized:
   Version: 0.3.1
   CUDA device: NVIDIA RTX 2000 Ada Generation Laptop GPU
   Kernel cache: $HOME/.cache/warp/0.3.1
2023-10-10 04:49:12,601 - mani_skill2 - INFO - load sdfs from file
Observation space Dict()
Action space Box(-1.0, 1.0, (8,), float32)
$HOME/.local/lib/python3.8/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.control_mode to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.control_mode` for environment variables or `env.get_wrapper_attr('control_mode')` that will search the reminding wrappers.
  logger.warn(
Control mode pd_joint_delta_pos
$HOME/.local/lib/python3.8/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.reward_mode to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.reward_mode` for environment variables or `env.get_wrapper_attr('reward_mode')` that will search the reminding wrappers.
  logger.warn(
Reward mode normalized_dense
nvrtc: error: invalid value for --gpu-architecture (-arch)
CUDA build failed
Module mpm.mpm_integrator load took 46.79 ms
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "$HOME/Projects/ManiSkill2/mani_skill2/examples/demo_random_action.py", line 78, in <module>
    main(parse_args())
  File "$HOME/Projects/ManiSkill2/mani_skill2/examples/demo_random_action.py", line 62, in main
    obs, reward, terminated, truncated, info = env.step(action)
  File "$HOME/.local/lib/python3.8/site-packages/gymnasium/wrappers/time_limit.py", line 57, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "$HOME/.local/lib/python3.8/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
  File "$HOME/Projects/ManiSkill2/mani_skill2/envs/mpm/base_env.py", line 570, in step
    obs, rew, terminated, truncated, info = super().step(action)
  File "$HOME/Projects/ManiSkill2/mani_skill2/envs/sapien_env.py", line 553, in step
    self.step_action(action)
  File "$HOME/Projects/ManiSkill2/mani_skill2/envs/mpm/base_env.py", line 594, in step_action
    self.mpm_simulator.simulate(
  File "$HOME/Projects/ManiSkill2/warp_maniskill/mpm/mpm_simulator.py", line 27, in simulate
    wp.launch(
  File "$HOME/Projects/ManiSkill2/warp_maniskill/warp/context.py", line 1108, in launch 
    success = kernel.module.load(device)
  File "$HOME/Projects/ManiSkill2/warp_maniskill/warp/context.py", line 692, in load
    raise(e)
  File "$HOME/Projects/ManiSkill2/warp_maniskill/warp/context.py", line 675, in load
    warp.build.build_cuda(cu_path, cuda_arch, ptx_path, config=self.options["mode"], verify_fp=warp.config.verify_fp)
  File "$HOME/Projects/ManiSkill2/warp_maniskill/warp/build.py", line 141, in build_cuda                                                
    raise Exception("CUDA build failed")
Exception: CUDA build failed
```

**Comment by xuanlinli17** [comment]
Interesting. This might be due to the specific GPU type you are using that is not compatible with the latest cuda.
