### ISSUE TITLE
`demos/rigid_body/PickSingleYCB-v0/035_power_drill.h5` doesn't exist but is used on the website

### ISSUE THREAD

**Issue by jstmn** [haosulab/ManiSkill#193]
Hi, 

I wanted to let y'all know that a command you have listed on your [website](https://maniskill2.github.io/) doesn't work. Specifically, running `python -m mani_skill2.trajectory.replay_trajectory --traj-path demos/rigid_body/PickSingleYCB-v0/035_power_drill.h5 --vis --bg-name minimal_bedroom` I get:
```
(venvTEMP) [ ~ ] $ python -m mani_skill2.trajectory.replay_trajectory --traj-path demos/rigid_body/PickSingleYCB-v0/035_power_drill.h5 --vis --bg-name minimal_bedroom
0step [00:00, ?step/s]Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jstm/venvTEMP/lib/python3.8/site-packages/mani_skill2/trajectory/replay_trajectory.py", line 530, in <module>
    main(parse_args())
  File "/home/jstm/venvTEMP/lib/python3.8/site-packages/mani_skill2/trajectory/replay_trajectory.py", line 524, in main
    _main(args)
  File "/home/jstm/venvTEMP/lib/python3.8/site-packages/mani_skill2/trajectory/replay_trajectory.py", line 338, in _main
    ori_h5_file = h5py.File(traj_path, "r")
  File "/home/jstm/venvTEMP/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/jstm/venvTEMP/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'demos/rigid_body/PickSingleYCB-v0/035_power_drill.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
0step [00:00, ?step/s]
```

I've already run
```
python -m mani_skill2.utils.download_asset ycb
python -m mani_skill2.utils.download_asset minimal_bedroom
python -m mani_skill2.utils.download_demo PickSingleYCB-v0
```

I'm able to playback other .h5 trajectories (like `demos/v0/rigid_body/PickSingleYCB-v0/021_bleach_cleanser.h5`) for reference. Looking through demos/v0/rigid_body/, I don't see `035_power_drill.h5`.

Thanks
- jeremy

**Comment by StoneT2000** [comment]
Looks like the website is out dated, the command should be

```
python -m mani_skill2.trajectory.replay_trajectory --traj-path demos/v0/rigid_body/PickSingleYCB-v0/035_power_drill.h5 --vis --bg-name minimal_bedroom
```

in the latest maniskill version we have decided to version the demonstration datasets. The website is now being updated, thanks for finding the bug!
