### ISSUE TITLE
IndexError: index out of bounds in ReplayBuffer

### ISSUE THREAD

**Issue by songyuc** [haosulab/ManiSkill#728]
## Issue Description
While running the SAC algorithm, I encountered an `IndexError` related to index out of bounds in the `ReplayBuffer`.

## Steps to Reproduce
Run the following command from [baselines/sac](https://github.com/haosulab/ManiSkill/tree/main/examples/baselines/sac):
```bash
python sac.py --env_id="PushCube-v1" \
  --num_envs=32 --utd=0.5 --buffer_size=500_000 \
  --total_timesteps=500_000 --eval_freq=50_000 --control-mode="pd_ee_delta_pos"
```
## Error Message
```bash
 python sac.py --env_id="PushCube-v1" \ze=500_000 \
  --num_envs=32 --utd=0.5 --buffer_size=500_000 \control-mode="
  --total_timesteps=500_000 --eval_freq=50_000 --control-mode="pd_ee_delta_pos"
2024-12-01 14:29:20,346 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:29:20,784 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
Saving eval trajectories/videos to runs/PushCube-v1__sac__1__1733034559/videos
/home/songyuc/anaconda3/envs/maniskill_env/lib/python3.11/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.max_episode_steps to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.max_episode_steps` for environment variables or `env.get_wrapper_attr('max_episode_steps')` that will search the reminding wrappers.
  logger.warn(
/home/songyuc/anaconda3/envs/maniskill_env/lib/python3.11/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.single_observation_space to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.single_observation_space` for environment variables or `env.get_wrapper_attr('single_observation_space')` that will search the reminding wrappers.
  logger.warn(
/home/songyuc/anaconda3/envs/maniskill_env/lib/python3.11/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.single_action_space to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.single_action_space` for environment variables or `env.get_wrapper_attr('single_action_space')` that will search the reminding wrappers.
  logger.warn(
Running training
2024-12-01 14:29:22,438 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
  0%|                               | 0/500000 [00:00<?, ?it/s]2024-12-01 14:29:22,847 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:29:26,887 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 0.00, return: 4.80:   0%| | 0/500000 [00:04<?, ?imodel saved to runs/PushCube-v1__sac__1__1733034559/ckpt_0.pt
success_once: 0.00, return: 4.80:  10%| | 50048/500000 [03:52<32024-12-01 14:33:15,943 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:33:20,006 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 34.60:  10%| | 50048/500000 [03:57<model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_50048.pt
success_once: 1.00, return: 34.60:  20%|▏| 100032/500000 [08:042024-12-01 14:37:27,816 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:37:31,915 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 0.94, return: 30.01:  20%|▏| 100032/500000 [08:09model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_100032.pt
success_once: 0.94, return: 30.01:  30%|▎| 150016/500000 [12:182024-12-01 14:41:41,388 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:41:45,496 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 0.94, return: 39.03:  30%|▎| 150016/500000 [12:23model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_150016.pt
success_once: 0.94, return: 39.03:  40%|▍| 200000/500000 [16:292024-12-01 14:45:52,207 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:45:56,291 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 44.00:  40%|▍| 200000/500000 [16:33model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_200000.pt
success_once: 1.00, return: 44.00:  50%|▌| 250048/500000 [20:422024-12-01 14:50:05,257 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:50:09,343 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 35.30:  50%|▌| 250048/500000 [20:46model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_250048.pt
success_once: 1.00, return: 35.30:  60%|▌| 300032/500000 [24:572024-12-01 14:54:20,515 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:54:24,663 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 35.55:  60%|▌| 300032/500000 [25:02model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_300032.pt
success_once: 1.00, return: 35.55:  70%|▋| 350016/500000 [29:102024-12-01 14:58:34,072 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 14:58:38,196 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 41.35:  70%|▋| 350016/500000 [29:15model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_350016.pt
success_once: 1.00, return: 41.35:  80%|▊| 400000/500000 [33:332024-12-01 15:02:56,727 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 15:03:01,190 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 43.97:  80%|▊| 400000/500000 [33:38model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_400000.pt
success_once: 1.00, return: 43.97:  90%|▉| 450048/500000 [37:562024-12-01 15:07:20,133 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
2024-12-01 15:07:24,508 - mani_skill  - WARNING - No initial pose set for actor builder of goal_region, setting to default pose q=[1,0,0,0], p=[0,0,0].
success_once: 1.00, return: 43.85:  90%|▉| 450048/500000 [38:02model saved to runs/PushCube-v1__sac__1__1733034559/ckpt_450048.pt
success_once: 1.00, return: 43.85: 100%|▉| 499968/500000 [42:15Traceback (most recent call last):
  File "/home/songyuc/Documents/Research/Robot_study/ManiSkill/examples/baselines/sac/sac.py", line 464, in <module>
    rb.add(obs, real_next_obs, actions, rewards, stop_bootstrap)
  File "/home/songyuc/Documents/Research/Robot_study/ManiSkill/examples/baselines/sac/sac.py", line 161, in add
    self.obs[self.pos] = obs
    ~~~~~~~~^^^^^^^^^^
IndexError: index 15625 is out of bounds for dimension 0 with size 15625
```
## Environment Information
- Python Version: 3.11
- Operating System: Ubuntu 20.04

**Comment by StoneT2000** [comment]
Fixed by #731
