### ISSUE TITLE
Failed to find a supported physical device "cuda:0" 

### ISSUE THREAD

**Issue by NirajPudasaini** [haosulab/ManiSkill#751]
(maniskill) niraj@mmvc:~/ManiSkill$ python -m mani_skill.examples.demo_random_action

Traceback (most recent call last):
  File "/home/niraj/anaconda3/envs/maniskill/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/niraj/anaconda3/envs/maniskill/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/niraj/ManiSkill/mani_skill/examples/demo_random_action.py", line 128, in <module>
    main(parsed_args)
  File "/home/niraj/ManiSkill/mani_skill/examples/demo_random_action.py", line 83, in main
    env: BaseEnv = gym.make(
  File "/home/niraj/anaconda3/envs/maniskill/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/niraj/ManiSkill/mani_skill/utils/registration.py", line 182, in make
    env = env_spec.make(**kwargs)
  File "/home/niraj/ManiSkill/mani_skill/utils/registration.py", line 79, in make
    return self.cls(**_kwargs)
  File "/home/niraj/ManiSkill/mani_skill/envs/tasks/tabletop/push_cube.py", line 65, in __init__
    super().__init__(*args, robot_uids=robot_uids, **kwargs)
  File "/home/niraj/ManiSkill/mani_skill/envs/sapien_env.py", line 338, in __init__
    obs, _ = self.reset(seed=[2022 + i for i in range(self.num_envs)], options=dict(reconfigure=True))
  File "/home/niraj/ManiSkill/mani_skill/envs/sapien_env.py", line 835, in reset
    self._reconfigure(options)
  File "/home/niraj/ManiSkill/mani_skill/envs/sapien_env.py", line 671, in _reconfigure
    self._setup_scene()
  File "/home/niraj/ManiSkill/mani_skill/envs/sapien_env.py", line 1108, in _setup_scene
    sapien.Scene([physx_system, sapien.render.RenderSystem(self._render_device)])
RuntimeError: Failed to find a supported physical device "cuda:0"
=====
I am trying to run on NVIDIA RTX 3080

**Comment by NirajPudasaini** [comment]
Resolved when reinstalled the GPU drivers.
