### ISSUE TITLE
RuntimeError: Cannot find a suitable rendering device

### ISSUE THREAD

**Issue by Jinming-Li** [haosulab/ManiSkill#97]
➜  /data/private/ljm/ManiSkill2 python                            
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import mani_skill2.envs  # import to register all environments in gym
>>> 
>>> env = gym.make("PickCube-v0", obs_mode="rgbd", control_mode="pd_ee_delta_pose")
{'offscreen_only': True}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/registration.py", line 73, in make
    env = self.entry_point(**_kwargs)
  File "/data/private/ljm/ManiSkill2/mani_skill2/utils/registration.py", line 92, in make
    env = env_spec.make(**kwargs)
  File "/data/private/ljm/ManiSkill2/mani_skill2/utils/registration.py", line 34, in make
    return self.cls(**_kwargs)
  File "/data/private/ljm/ManiSkill2/mani_skill2/envs/pick_and_place/pick_cube.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "/data/private/ljm/ManiSkill2/mani_skill2/envs/pick_and_place/base_env.py", line 27, in __init__
    super().__init__(*args, **kwargs)
  File "/data/private/ljm/ManiSkill2/mani_skill2/envs/sapien_env.py", line 106, in __init__
    self._renderer = sapien.SapienRenderer(**renderer_kwargs)
RuntimeError: Cannot find a suitable rendering device

**Comment by xuanlinli17** [comment]
See https://github.com/haosulab/ManiSkill2/issues/92
