### ISSUE TITLE
ModuleNotFoundError: No module named 'warp' while compiling soft body environments.

### ISSUE THREAD

**Issue by Kami-code** [haosulab/ManiSkill#98]
Hi. Recently, I faced this error when trying to compile the soft-body environments. I follow the commands in [https://haosulab.github.io/ManiSkill2/getting_started/installation.html#warp-maniskill2-version](https://haosulab.github.io/ManiSkill2/getting_started/installation.html#warp-maniskill2-version) . Do I need to manually install wrap-lang module ? If so , which version should I install? 

```
root@baochen-template-create:/baochen/ManiSkill2# export CUDA_PATH=/usr/local/cuda
root@baochen-template-create:/baochen/ManiSkill2# ${CUDA_PATH}/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
root@baochen-template-create:/baochen/ManiSkill2# gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
root@baochen-template-create:/baochen/ManiSkill2# python3 -m warp_maniskill.build_lib
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/baochen/ManiSkill2/warp_maniskill/build_lib.py", line 12, in <module>
    import warp.config
ModuleNotFoundError: No module named 'warp'

```

**Comment by xuanlinli17** [comment]
Try

export PYTHONPATH="$PWD"/warp_maniskill:$PYTHONPATH; python -m warp_maniskill.build_lib

we'll update readme later
